name: Helm Chart - Validate
on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint Helm
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint ./livekit-server

      - name: Validate
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ./