name: Helm Chart - Validate
on:
  push:
    branches: [ main, master ]

  pull_request:
    branches: [ main, master ]

  workflow_dispatch:
jobs:
  lint-helm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Lint Helm (livekit-server)
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint ./charts/livekit-server

      - name: Lint Helm (egress)
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint ./charts/egress

      - name: Lint Helm (ingress)
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: helm lint ./charts/ingress

      - name: Validate
        uses: nlamirault/helm-kubeconform-action@v0.1.0
        with:
          charts: ./charts